#pragma once
#ifndef __ENUM_H_
#define __ENUM_H_

namespace BULLET
{
	enum DIR { LEFT, RIGHT, UP, DOWN, END};
}

namespace OBJID
{
										//낫 콜리전 몬스터는 충돌처리가 되지 않아서 어떤 공격도 맞지않음 UI로 만들려다가 그냥 enum 하나 추가하면 될일이니 만듬
	enum ID { OVER_PLAYER,PLAYER,PLAYER_BULLET,MONSTER,MONSTER_BULLET,MONSTER_COLLISION_BULLET, NOT_COLLISION_MONSTER, LINE,MYRECT, UI,WORLDUI,END };
}

enum SCENEID { SCENE_LOGO, SCENE_MENU, SCENE_OVERWORLD, SCENE_EDIT, SCENE_STAGEFARM, SCENE_STAGEFLOWER, SCENE_STAGESLIME, SCENE_STAGECLEAR , SCENE_END };

//Y소팅할 때 쓰임
enum RENDERID { RENDER_BACK, RENDER_OBJ, RENDER_EFFECT, RENDER_UI, RENDER_END };

#endif